src/Entity/Invoice.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Table(name="invoice")
 * @ORM\Entity(repositoryClass="App\Repository\InvoiceRepository")
 */
class Invoice
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client")
     * @ORM\JoinColumn(name="client_id", referencedColumnName="client_id",nullable=false)
     */
    private $client_id;
    /**
     * @ORM\Column(type="string", length=40)
     */
    private $invoice_nr;
    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime")
     */
    private $timestamp;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="create_user", referencedColumnName="id",nullable=false)
     */
    private $create_user;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * @param mixed $client_id
     */
    public function setClientId($client_id)
    {
        $this->client_id = $client_id;
    }

    /**
     * @return mixed
     */
    public function getInvoiceNr()
    {
        return $this->invoice_nr;
    }

    /**
     * @param mixed $invoice_nr
     */
    public function setInvoiceNr($invoice_nr)
    {
        $this->invoice_nr = $invoice_nr;
    }

    /**
     * @return mixed
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param mixed $comment
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
    }

    /**
     * @param mixed $total_net_amount
     */
    public function setTotalNetAmount($total_net_amount)
    {
        $this->total_net_amount = $total_net_amount;
    }

    /**
     * @param mixed $total_tax_amount
     */
    public function setTotalTaxAmount($total_tax_amount)
    {
        $this->total_tax_amount = $total_tax_amount;
    }

    /**
     * @param mixed $total_gross_amount
     */
    public function setTotalGrossAmount($total_gross_amount)
    {
        $this->total_gross_amount = $total_gross_amount;
    }

    /**
     * @return mixed
     */
    public function getTimeStamp()
    {
        if( is_null($this->timestamp) || !$this->timestamp instanceof \DateTime )
        {
            return '';
        }
        return $this->timestamp->format('Y-m-d');
    }

    /**
     * @param mixed $create_date
     */
    public function setCreateDate($create_date)
    {
        $this->create_date = $create_date;
    }

    /**
     * @return mixed
     */
    public function getCreateUser(): ?User
    {
        return $this->create_user;
    }

    /**
     * @param mixed $create_user_id
     */
    public function setCreateUser(?User $create_user_id): self
    {
        $this->create_user = $create_user_id;

        return $this;
    }

    /**
     * @param mixed $timestamp
     */
    public function setTimestamp($timestamp=null)
    {
        if(is_null($timestamp)) $timestamp = new \DateTime();

        $this->timestamp = $timestamp;
    }

}

src/Controller/InvoiceController.php
<?php
// src/Controller/LuckyController.php
namespace App\Controller;

use App\Entity\Invoice;
use App\Entity\Menu;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\Product;

class InvoiceController extends Controller
{
    public function list()
    {
        $invoices = $this->getDoctrine()->getRepository(Invoice::class)
            ->findAll();

        $repo = $this->getDoctrine()
            ->getRepository(Menu::class);

        $menu = new Menu($repo);

        return $this->render('invoice/list.html.twig', array(
            'headers' => ['id','client_id','invoice_nr','comment','create_user','timestamp'],
            'invoices'=>$invoices,
            'menu' => $menu->getList()
        ));

        /*return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );*/
    }
}

templates/invoice/list.html.twig
{% extends ["layouts/main_theme.html.twig"] %}

{% block body %}

    <div id="pad"></div>

    <div id="initialData" class="end hide" >
        <table>
            <thead>
                <tr>
                    {% for head in headers %}
                        <th data-id="{{ head }}" >{{ head }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for invoice in invoices %}
                    <tr>
                        <td data-id="id">{{ invoice.id }}</td>
                        <td data-id="client_id">{{ invoice.clientId }}</td>
                        <td data-id="invoice_nr">{{ invoice.invoiceNr }}</td>
                        <td data-id="comment">{{ invoice.comment }}</td>
                        <td data-id="create_user">{{ invoice.createUser }}</td>
                        <td data-id="timestamp">{{ invoice.timeStamp }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <style>
        #pad a{
            padding: 5px;
            color: white;
            background: black;
            border-radius: 34%;
            margin: 10px;
        }
    </style>

{% endblock %}

        {% block javascripts %}
            {{ parent() }}
            <script src="{{ asset('build/jsx/app.js')~'?v='~'now'|date('Y-m-d H:i:s') }}"></script>
        {% endblock %}